In [4]:
import numpy as np

X = [[22.3,-1.5, 1.1, 1]]
theta = [0.1,-0.15, 0.3,-0.2]

def predict(X, theta):
  z = np.dot(X, theta)
  return 1 / (1 + np.exp(-z))

prediction = predict(X, theta)
prediction

array([0.92988994])

In [5]:
y = np.array([1, 0, 0, 1])
y_hat = np.array([0.8, 0.75, 0.3,0.95])

def compute_loss(y_hat, y):
  y_hat = np.clip(y_hat, 1e-7, 1- 1e-7)
  return (-y * np.log(y_hat)- (1- y) * np.log(1- y_hat)).mean()

loss = compute_loss(y_hat, y)
loss

0.5043515376900958

In [9]:
X = np.array([[1, 2], [2, 1], [1, 1], [2, 2]])
y_true = np.array([0, 1, 0, 1])
y_pred = np.array([0.25, 0.75, 0.4, 0.8])

def compute_gradient(X, y_true, y_pred):
    gradient = np.dot(X.T, (y_pred - y_true)) / y_true.size
    return gradient

gradient = compute_gradient(X, y_true, y_pred)
gradient

array([-0.0625,  0.0625])

In [10]:
def compute_accuracy(y_true, y_pred):
    y_pred_rounded = np.round(y_pred)
    accuracy = np.mean(y_true == y_pred_rounded)
    return accuracy

y_true_accuracy = np.array([1, 0, 1, 1])
y_pred_accuracy = np.array([0.85, 0.35, 0.9, 0.75])
accuracy_result = compute_accuracy(y_true_accuracy, y_pred_accuracy)

accuracy_result

1.0

In [11]:
def compute_gradient(X, y_true, y_pred):
    gradient = np.dot(X.T, (y_pred - y_true)) / y_true.size
    return gradient

X_gradient = np.array([[1, 3], [2, 1], [3, 2], [1, 2]])
y_true_gradient = np.array([1, 0, 1, 1])
y_pred_gradient = np.array([0.7, 0.4, 0.6, 0.85])
gradient_result = compute_gradient(X_gradient,
                                   y_true_gradient,
                                   y_pred_gradient)

gradient_result

array([-0.2125, -0.4   ])