In [1]:
import torch
import torch.nn as nn
import numpy as np

# Input data as a numpy array
data = np.array([[[1, 6], [3, 4]]], dtype=np.float32)

# Convert data to a PyTorch tensor
data = torch.tensor(data)

# Define Batch Normalization with 1 channel
bnorm = nn.BatchNorm2d(1)

# Add a batch dimension
data = data.unsqueeze(0)

# Apply BatchNorm without gradient computation
with torch.no_grad():
    output = bnorm(data)

# Print the output
print(output)

tensor([[[[-1.3867,  1.3867],
          [-0.2773,  0.2773]]]])


In [2]:
import torch

# Define two tensors
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])

# Reshape tensors to include a batch dimension
a = a.reshape(1, 2, 2)
b = b.reshape(1, 2, 2)

# Concatenate the tensors along the first dimension
c = torch.cat((a, b))

# Print the result
print(c)

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])


In [5]:
import torch
import torch.nn as nn

# Set random seed for reproducibility
seed = 1
torch.manual_seed(seed)

# Define input tensor
input_tensor = torch.tensor([[[[1.0, 2.0], [3.0, 4.0]]]])

# Define a 2D convolutional layer
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2)

# Compute convolution output
conv_output = conv_layer(input_tensor)

# Add input tensor and convolution output without gradient computation
with torch.no_grad():
    output = conv_output + input_tensor

# Print the result
print(output)

tensor([[[[0.9935, 1.9935],
          [2.9935, 3.9935]]]])
