In [1]:
# The lenghth of vector
import numpy as np
def compute_vector_length(vector):
  len_of_vector = np.linalg.norm(vector)
  return len_of_vector

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result,2))
# D

23.28


In [2]:
# The dot of product
import numpy as np
def compute_dot_product(u, v):
  dot_product = np.dot(u, v)
  return dot_product

v1 = np.array([0, 1,-1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result,2))
# B

4


In [6]:
# The multiplication of matrix and vector
import numpy as np
def compute_matrix_vector_product(matrix, vector):
  matrix_vector_product = np.dot(matrix, vector)
  return matrix_vector_product

x = np.array([[1, 2], [3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))
# A

a = np.array([[-1, 2],[3, -4]])
b = np.array([1, 2])
print('result \n', a @ b)
# B

m = np.array([[-1, 1, 1], [0,-4, 9]])
v = np.array([0, 2, 1])
result = compute_matrix_vector_product(m, v)
print('result \n',result)
# A

result 
 [ 5 11]
result 
 [ 3 -5]
result 
 [3 1]


In [9]:
import numpy as np

def compute_matrix_matrix_product(matrix1, matrix2):
    matrix_matrix_product = np.dot(matrix1, matrix2)
    return matrix_matrix_product

# First matrix multiplication
m1 = np.array([[0, 1, 2],
               [2, -3, 1]])
m2 = np.array([[1, -3],
               [6, 1],
               [0, -1]])

result = compute_matrix_matrix_product(m1, m2)
print("First result:\n", result)
# C

# Second matrix multiplication
m3 = np.eye(3)
m4 = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

result = m3 @ m4
print("Second result:\n", result)
# A

# Third matrix multiplication
m5 = np.eye(2)
m5 = np.reshape(m5, (-1, 4))[0]
m6 = np.array([[1, 1, 1, 1],
               [2, 2, 2, 2],
               [3, 3, 3, 3],
               [4, 4, 4, 4]])

result = m5 @ m6
print("Third result:\n", result)
# D

# Fourth matrix multiplication
m7 = np.array([[1, 2],
               [3, 4]])
m7 = np.reshape(m7, (-1, 4), order='F')[0]
m8 = np.array([[1, 1, 1, 1],
               [2, 2, 2, 2],
               [3, 3, 3, 3],
               [4, 4, 4, 4]])

result = m7 @ m8
print("Fourth result:\n", result)
# B

First result:
 [[  6  -1]
 [-16 -10]]
Second result:
 [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
Third result:
 [5. 5. 5. 5.]
Fourth result:
 [29 29 29 29]


In [10]:
# The reversal matrix
import numpy as np
def compute_matrix_reversal(matrix):
  matrix_reversal = np.linalg.inv(matrix)
  return matrix_reversal

m1 = np.array([[-2, 6], [8,-4]])
result = compute_matrix_reversal(m1)
print(result)
# A

[[0.1  0.15]
 [0.2  0.05]]
